# Generated by Django 5.1.2 on 2024-10-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("dept_id", models.AutoField(primary_key=True, serialize=False)),
                ("dept_name", models.CharField(max_length=100)),
            ],
        ),
    ]
