# Generated by Django 5.1.2 on 2024-10-18 17:47

import django.db.models.deletion
import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "emp_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("position", models.CharField(max_length=100)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "hire_date",
                    models.DateField(validators=[employee.models.validate_hire_date]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.department",
                    ),
                ),
            ],
        ),
    ]
