# Generated by Django 5.1.2 on 2024-10-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(max_length=100),
        ),
    ]
