# Generated by Django 5.1.2 on 2024-10-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_remove_employee_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.IntegerField(),
        ),
    ]
